# Generated by Django 5.2.15 on 2026-08-08 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_bookings_se_start_d_idx_bookings_se_start_d_80a456_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='seva',
            name='bookings_se_start_d_80a456_idx',
        ),
        migrations.RemoveIndex(
            model_name='seva',
            name='bookings_se_is_acti_c04527_idx',
        ),
        migrations.RemoveField(
            model_name='seva',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='seva',
            name='start_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
