# Generated by Django 5.2.15 on 2026-08-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_remove_seva_bookings_se_start_d_80a456_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seva',
            old_name='seva_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='seva',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
